import type { ReviewRecord } from "@/lib/reviews/types";

export const curatedReviews: ReviewRecord[] = [
  {
    id: "curated-ru-audi-a4",
    name: "Audi A4",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "Перед началом работы всё понятно объяснили по ремонту и стоимости. Машину Виталий сделал в согласованный срок. Результат аккуратный, после получения автомобиля никаких дополнительных вопросов не возникло.",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-12T12:00:00.000Z",
    updatedAt: "2026-07-12T12:00:00.000Z",
  },
  {
    id: "curated-ru-bmw-3-series",
    name: "BMW 3 Series",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "Сначала сомневался, потому что боялся, что будет заметна разница в цвете. В итоге всё получилось отлично: поверхность ровная, оттенок совпал, следов ремонта не видно.",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-11T12:00:00.000Z",
    updatedAt: "2026-07-11T12:00:00.000Z",
  },
  {
    id: "curated-ru-volkswagen-golf",
    name: "Volkswagen Golf",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "Обратился для восстановления кузова автомобиля, на котором было много мелких повреждений. После ремонта и покраски машина стала выглядеть значительно лучше и свежее.",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-10T12:00:00.000Z",
    updatedAt: "2026-07-10T12:00:00.000Z",
  },
  {
    id: "curated-ru-mercedes-benz-c-class",
    name: "Mercedes-Benz C-Class",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "Красили сразу несколько элементов кузова. Все детали подготовлены аккуратно, цвет получился одинаковым, зазоры и внешний вид автомобиля сохранились. Результат оправдал ожидания.",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-09T12:00:00.000Z",
    updatedAt: "2026-07-09T12:00:00.000Z",
  },
  {
    id: "curated-ru-ford-focus",
    name: "Ford Focus",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "На крыше было повреждено лакокрасочное покрытие. Всё хорошо подготовили и перекрасили. Поверхность ровная, без заметных дефектов. Качеством работы доволен.",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-08T12:00:00.000Z",
    updatedAt: "2026-07-08T12:00:00.000Z",
  },
  {
    id: "curated-ru-toyota-corolla",
    name: "Toyota Corolla",
    rating: 5,
    service: "Покраска и кузовной ремонт",
    text: "Виталий — хороший маляр. Работа выполнена аккуратно и качественно. Спасибо!",
    locale: "ru",
    status: "approved",
    createdAt: "2026-07-07T12:00:00.000Z",
    updatedAt: "2026-07-07T12:00:00.000Z",
  },
];
