const errors = {
  nb: { invalid: "Kontroller de obligatoriske feltene.", html: "HTML og kode er ikke tillatt.", rate: "For mange forsøk. Prøv igjen senere.", storage: "Anmeldelsestjenesten er midlertidig utilgjengelig.", server: "Anmeldelsen kunne ikke sendes. Prøv igjen." },
  fi: { invalid: "Tarkista pakolliset kentät.", html: "HTML ja koodi eivät ole sallittuja.", rate: "Liian monta yritystä. Yritä myöhemmin uudelleen.", storage: "Arvostelupalvelu ei ole tilapäisesti käytettävissä.", server: "Arvostelua ei voitu lähettää. Yritä uudelleen." },
  da: { invalid: "Kontrollér de obligatoriske felter.", html: "HTML og kode er ikke tilladt.", rate: "For mange forsøg. Prøv igen senere.", storage: "Anmeldelsestjenesten er midlertidigt utilgængelig.", server: "Anmeldelsen kunne ikke sendes. Prøv igen." },
  sv: { invalid: "Kontrollera de obligatoriska fälten.", html: "HTML och kod är inte tillåtna.", rate: "För många försök. Försök igen senare.", storage: "Omdömestjänsten är tillfälligt otillgänglig.", server: "Omdömet kunde inte skickas. Försök igen." },
  sk: { invalid: "Skontrolujte povinné polia.", html: "HTML ani kód nie sú povolené.", rate: "Príliš veľa pokusov. Skúste to neskôr.", storage: "Služba hodnotení je dočasne nedostupná.", server: "Hodnotenie sa nepodarilo odoslať. Skúste to znova." },
  hu: { invalid: "Ellenőrizze a kötelező mezőket.", html: "HTML és programkód nem engedélyezett.", rate: "Túl sok próbálkozás. Próbálja újra később.", storage: "Az értékelési szolgáltatás átmenetileg nem érhető el.", server: "Az értékelést nem sikerült elküldeni. Próbálja újra." },
  bg: { invalid: "Проверете задължителните полета.", html: "HTML и програмен код не са разрешени.", rate: "Твърде много опити. Опитайте по-късно.", storage: "Услугата за отзиви временно не е достъпна.", server: "Отзивът не можа да бъде изпратен. Опитайте отново." },
  pt: { invalid: "Verifique os campos obrigatórios.", html: "HTML e código não são permitidos.", rate: "Demasiadas tentativas. Tente mais tarde.", storage: "O serviço de avaliações está temporariamente indisponível.", server: "Não foi possível enviar a avaliação. Tente novamente." },
  el: { invalid: "Ελέγξτε τα υποχρεωτικά πεδία.", html: "Δεν επιτρέπονται HTML και κώδικας.", rate: "Πάρα πολλές προσπάθειες. Δοκιμάστε αργότερα.", storage: "Η υπηρεσία αξιολογήσεων δεν είναι προσωρινά διαθέσιμη.", server: "Η αξιολόγηση δεν στάλθηκε. Δοκιμάστε ξανά." },
  cs: { invalid: "Zkontrolujte povinná pole.", html: "HTML ani kód nejsou povoleny.", rate: "Příliš mnoho pokusů. Zkuste to později.", storage: "Služba hodnocení je dočasně nedostupná.", server: "Hodnocení se nepodařilo odeslat. Zkuste to znovu." },
} as const;

export const additionalReviewTranslations = {
  nb: { title: "Kundeanmeldelser", intro: "Ekte tilbakemeldinger om arbeidet og kvaliteten vår", showAll: "Vis alle anmeldelser", showLess: "Vis færre", empty: "Godkjente anmeldelser vises her.", formTitle: "Skriv en anmeldelse", formIntro: "Del erfaringen din og hjelp andre kunder med å ta et godt valg.", name: "Navnet ditt", rating: "Vurdering", service: "Arbeid / Bil", optional: "valgfritt", review: "Din anmeldelse", consent: "Jeg godtar", privacy: "personvernerklæringen", submit: "Send anmeldelse", sending: "Sender...", moderation: "Anmeldelsen sendes til moderering og publiseres etter kontroll.", success: "Takk! Anmeldelsen er sendt til moderering.", trustTitle: "Hvorfor kundene velger oss", trustItems: ["Profesjonelle materialer", "Sans for detaljer", "Fagmessig arbeid"], errors: errors.nb },
  fi: { title: "Asiakasarviot", intro: "Aitoja kokemuksia työstämme ja palvelumme laadusta", showAll: "Näytä kaikki arviot", showLess: "Näytä vähemmän", empty: "Hyväksytyt arviot näkyvät täällä.", formTitle: "Jätä arvio", formIntro: "Kerro kokemuksestasi ja auta muita asiakkaita tekemään hyvä valinta.", name: "Nimesi", rating: "Arvosana", service: "Työ / Auto", optional: "valinnainen", review: "Arviosi", consent: "Hyväksyn", privacy: "tietosuojakäytännön", submit: "Lähetä arvio", sending: "Lähetetään...", moderation: "Arvio lähetetään tarkistettavaksi ja julkaistaan hyväksynnän jälkeen.", success: "Kiitos! Arviosi on lähetetty tarkistettavaksi.", trustTitle: "Miksi asiakkaat valitsevat meidät", trustItems: ["Ammattimateriaalit", "Huolellinen työnjälki", "Ammattimainen työ"], errors: errors.fi },
  da: { title: "Kundeanmeldelser", intro: "Ægte tilbagemeldinger om vores arbejde og kvalitet", showAll: "Se alle anmeldelser", showLess: "Vis færre", empty: "Godkendte anmeldelser vises her.", formTitle: "Skriv en anmeldelse", formIntro: "Del din oplevelse og hjælp andre kunder med at træffe et godt valg.", name: "Dit navn", rating: "Bedømmelse", service: "Arbejde / Bil", optional: "valgfrit", review: "Din anmeldelse", consent: "Jeg accepterer", privacy: "privatlivspolitikken", submit: "Send anmeldelse", sending: "Sender...", moderation: "Anmeldelsen sendes til godkendelse og offentliggøres efter kontrol.", success: "Tak! Din anmeldelse er sendt til godkendelse.", trustTitle: "Hvorfor kunder vælger os", trustItems: ["Professionelle materialer", "Sans for detaljer", "Fagligt arbejde"], errors: errors.da },
  sv: { title: "Kundomdömen", intro: "Äkta omdömen om vårt arbete och vår kvalitet", showAll: "Visa alla omdömen", showLess: "Visa färre", empty: "Godkända omdömen visas här.", formTitle: "Lämna ett omdöme", formIntro: "Dela din erfarenhet och hjälp andra kunder att göra ett bra val.", name: "Ditt namn", rating: "Betyg", service: "Arbete / Bil", optional: "valfritt", review: "Ditt omdöme", consent: "Jag godkänner", privacy: "integritetspolicyn", submit: "Skicka omdöme", sending: "Skickar...", moderation: "Omdömet granskas och publiceras efter godkännande.", success: "Tack! Ditt omdöme har skickats för granskning.", trustTitle: "Varför kunder väljer oss", trustItems: ["Professionella material", "Noggrannhet", "Fackmässigt arbete"], errors: errors.sv },
  sk: { title: "Hodnotenia zákazníkov", intro: "Skutočné hodnotenia našej práce a kvality", showAll: "Zobraziť všetky hodnotenia", showLess: "Zobraziť menej", empty: "Schválené hodnotenia sa zobrazia tu.", formTitle: "Pridať hodnotenie", formIntro: "Podeľte sa o skúsenosť a pomôžte ďalším zákazníkom pri výbere.", name: "Vaše meno", rating: "Hodnotenie", service: "Práca / Vozidlo", optional: "voliteľné", review: "Vaše hodnotenie", consent: "Súhlasím so", privacy: "zásadami ochrany súkromia", submit: "Odoslať hodnotenie", sending: "Odosiela sa...", moderation: "Hodnotenie bude po kontrole schválené a zverejnené.", success: "Ďakujeme! Hodnotenie bolo odoslané na kontrolu.", trustTitle: "Prečo si nás zákazníci vyberajú", trustItems: ["Profesionálne materiály", "Dôraz na detail", "Odborná práca"], errors: errors.sk },
  hu: { title: "Ügyfélértékelések", intro: "Valós visszajelzések munkánkról és annak minőségéről", showAll: "Összes értékelés", showLess: "Kevesebb mutatása", empty: "A jóváhagyott értékelések itt jelennek meg.", formTitle: "Értékelés írása", formIntro: "Ossza meg tapasztalatát, és segítsen más ügyfeleknek a választásban.", name: "Az Ön neve", rating: "Értékelés", service: "Munka / Autó", optional: "nem kötelező", review: "Véleménye", consent: "Elfogadom az", privacy: "adatvédelmi szabályzatot", submit: "Értékelés küldése", sending: "Küldés...", moderation: "Az értékelést ellenőrizzük, és jóváhagyás után közzétesszük.", success: "Köszönjük! Értékelése ellenőrzésre elküldve.", trustTitle: "Miért választanak minket", trustItems: ["Professzionális anyagok", "Figyelem a részletekre", "Szakszerű munka"], errors: errors.hu },
  bg: { title: "Отзиви от клиенти", intro: "Реални мнения за нашата работа и качество", showAll: "Вижте всички отзиви", showLess: "Покажете по-малко", empty: "Одобрените отзиви ще се показват тук.", formTitle: "Оставете отзив", formIntro: "Споделете опита си и помогнете на други клиенти да направят добър избор.", name: "Вашето име", rating: "Оценка", service: "Работа / Автомобил", optional: "по желание", review: "Вашият отзив", consent: "Съгласен съм с", privacy: "политиката за поверителност", submit: "Изпратете отзив", sending: "Изпращане...", moderation: "Отзивът се проверява и публикува след одобрение.", success: "Благодарим! Отзивът е изпратен за проверка.", trustTitle: "Защо клиентите ни избират", trustItems: ["Професионални материали", "Внимание към детайла", "Професионална работа"], errors: errors.bg },
  pt: { title: "Avaliações de clientes", intro: "Opiniões reais sobre o nosso trabalho e qualidade", showAll: "Ver todas as avaliações", showLess: "Mostrar menos", empty: "As avaliações aprovadas aparecerão aqui.", formTitle: "Deixar uma avaliação", formIntro: "Partilhe a sua experiência e ajude outros clientes a escolher.", name: "O seu nome", rating: "Classificação", service: "Trabalho / Veículo", optional: "opcional", review: "A sua avaliação", consent: "Aceito a", privacy: "política de privacidade", submit: "Enviar avaliação", sending: "A enviar...", moderation: "A avaliação será verificada e publicada após aprovação.", success: "Obrigado! A avaliação foi enviada para verificação.", trustTitle: "Porque os clientes nos escolhem", trustItems: ["Materiais profissionais", "Atenção ao detalhe", "Trabalho especializado"], errors: errors.pt },
  el: { title: "Αξιολογήσεις πελατών", intro: "Πραγματικές απόψεις για την εργασία και την ποιότητά μας", showAll: "Όλες οι αξιολογήσεις", showLess: "Λιγότερες αξιολογήσεις", empty: "Οι εγκεκριμένες αξιολογήσεις θα εμφανίζονται εδώ.", formTitle: "Γράψτε αξιολόγηση", formIntro: "Μοιραστείτε την εμπειρία σας και βοηθήστε άλλους πελάτες να επιλέξουν.", name: "Το όνομά σας", rating: "Βαθμολογία", service: "Εργασία / Όχημα", optional: "προαιρετικό", review: "Η αξιολόγησή σας", consent: "Αποδέχομαι την", privacy: "πολιτική απορρήτου", submit: "Αποστολή αξιολόγησης", sending: "Αποστολή...", moderation: "Η αξιολόγηση ελέγχεται και δημοσιεύεται μετά την έγκριση.", success: "Ευχαριστούμε! Η αξιολόγηση στάλθηκε για έλεγχο.", trustTitle: "Γιατί μας επιλέγουν", trustItems: ["Επαγγελματικά υλικά", "Προσοχή στη λεπτομέρεια", "Εξειδικευμένη εργασία"], errors: errors.el },
  cs: { title: "Hodnocení zákazníků", intro: "Skutečná hodnocení naší práce a její kvality", showAll: "Zobrazit všechna hodnocení", showLess: "Zobrazit méně", empty: "Schválená hodnocení se zobrazí zde.", formTitle: "Přidat hodnocení", formIntro: "Podělte se o zkušenost a pomozte dalším zákazníkům s výběrem.", name: "Vaše jméno", rating: "Hodnocení", service: "Práce / Vozidlo", optional: "volitelné", review: "Vaše hodnocení", consent: "Souhlasím se", privacy: "zásadami ochrany soukromí", submit: "Odeslat hodnocení", sending: "Odesílání...", moderation: "Hodnocení bude po kontrole schváleno a zveřejněno.", success: "Děkujeme! Hodnocení bylo odesláno ke kontrole.", trustTitle: "Proč si nás zákazníci vybírají", trustItems: ["Profesionální materiály", "Důraz na detail", "Odborná práce"], errors: errors.cs },
} as const;
