import type { Locale } from "@/config/i18n";

type InterfaceCopy = {
  mainNavigation: string;
  languageMenu: string;
  menu: string;
  footerNavigation: string;
  footerLinks: readonly [string, string, string, string, string, string, string, string];
  whatsappLabel: string;
  faqHeading: string;
  notFoundBack: string;
  dateLocale: string;
  ratingAction: string;
  ratingOutOfFive: string;
};

export const interfaceTranslations: Record<Locale, InterfaceCopy> = {
  es: { mainNavigation: "Navegación principal", languageMenu: "Idioma", menu: "Menú", footerNavigation: "Secciones del sitio", footerLinks: ["Servicios", "Ciudades", "Marcas", "Trabajos", "Blog", "FAQ", "Contacto", "Sobre nosotros"], whatsappLabel: "Escribir a PaintLab Torrevieja por WhatsApp", faqHeading: "Preguntas frecuentes", notFoundBack: "Volver al inicio", dateLocale: "es-ES", ratingAction: "Dar una valoración de {rating} sobre 5", ratingOutOfFive: "de 5" },
  en: { mainNavigation: "Main navigation", languageMenu: "Language", menu: "Menu", footerNavigation: "Site sections", footerLinks: ["Services", "Cities", "Makes", "Work", "Blog", "FAQ", "Contact", "About us"], whatsappLabel: "Message PaintLab Torrevieja on WhatsApp", faqHeading: "Frequently asked questions", notFoundBack: "Back to home", dateLocale: "en-GB", ratingAction: "Set rating to {rating} out of 5", ratingOutOfFive: "out of 5" },
  ru: { mainNavigation: "Основная навигация", languageMenu: "Язык", menu: "Меню", footerNavigation: "Разделы сайта", footerLinks: ["Услуги", "Города", "Марки", "Работы", "Блог", "FAQ", "Контакты", "О нас"], whatsappLabel: "Написать PaintLab Torrevieja в WhatsApp", faqHeading: "Частые вопросы", notFoundBack: "Вернуться на главную", dateLocale: "ru-RU", ratingAction: "Поставить оценку {rating} из 5", ratingOutOfFive: "из 5" },
  uk: { mainNavigation: "Основна навігація", languageMenu: "Мова", menu: "Меню", footerNavigation: "Розділи сайту", footerLinks: ["Послуги", "Міста", "Марки", "Роботи", "Блог", "FAQ", "Контакти", "Про нас"], whatsappLabel: "Написати PaintLab Torrevieja у WhatsApp", faqHeading: "Часті запитання", notFoundBack: "Повернутися на головну", dateLocale: "uk-UA", ratingAction: "Поставити оцінку {rating} із 5", ratingOutOfFive: "із 5" },
  de: { mainNavigation: "Hauptnavigation", languageMenu: "Sprache", menu: "Menü", footerNavigation: "Website-Bereiche", footerLinks: ["Leistungen", "Städte", "Marken", "Arbeiten", "Blog", "FAQ", "Kontakt", "Über uns"], whatsappLabel: "PaintLab Torrevieja auf WhatsApp schreiben", faqHeading: "Häufige Fragen", notFoundBack: "Zur Startseite", dateLocale: "de-DE", ratingAction: "Bewertung auf {rating} von 5 setzen", ratingOutOfFive: "von 5" },
  fr: { mainNavigation: "Navigation principale", languageMenu: "Langue", menu: "Menu", footerNavigation: "Rubriques du site", footerLinks: ["Services", "Villes", "Marques", "Réalisations", "Blog", "FAQ", "Contact", "À propos"], whatsappLabel: "Écrire à PaintLab Torrevieja sur WhatsApp", faqHeading: "Questions fréquentes", notFoundBack: "Retour à l’accueil", dateLocale: "fr-FR", ratingAction: "Attribuer une note de {rating} sur 5", ratingOutOfFive: "sur 5" },
  pl: { mainNavigation: "Nawigacja główna", languageMenu: "Język", menu: "Menu", footerNavigation: "Sekcje strony", footerLinks: ["Usługi", "Miasta", "Marki", "Realizacje", "Blog", "FAQ", "Kontakt", "O nas"], whatsappLabel: "Napisz do PaintLab Torrevieja na WhatsApp", faqHeading: "Najczęstsze pytania", notFoundBack: "Powrót na stronę główną", dateLocale: "pl-PL", ratingAction: "Ustaw ocenę {rating} na 5", ratingOutOfFive: "na 5" },
  nl: { mainNavigation: "Hoofdnavigatie", languageMenu: "Taal", menu: "Menu", footerNavigation: "Website-onderdelen", footerLinks: ["Diensten", "Steden", "Merken", "Werk", "Blog", "FAQ", "Contact", "Over ons"], whatsappLabel: "Stuur PaintLab Torrevieja een WhatsApp-bericht", faqHeading: "Veelgestelde vragen", notFoundBack: "Terug naar home", dateLocale: "nl-NL", ratingAction: "Beoordeling instellen op {rating} van 5", ratingOutOfFive: "van 5" },
  it: { mainNavigation: "Navigazione principale", languageMenu: "Lingua", menu: "Menu", footerNavigation: "Sezioni del sito", footerLinks: ["Servizi", "Città", "Marche", "Lavori", "Blog", "FAQ", "Contatti", "Chi siamo"], whatsappLabel: "Scrivi a PaintLab Torrevieja su WhatsApp", faqHeading: "Domande frequenti", notFoundBack: "Torna alla home", dateLocale: "it-IT", ratingAction: "Imposta la valutazione su {rating} su 5", ratingOutOfFive: "su 5" },
  nb: { mainNavigation: "Hovednavigasjon", languageMenu: "Språk", menu: "Meny", footerNavigation: "Nettstedsseksjoner", footerLinks: ["Tjenester", "Byer", "Bilmerker", "Arbeid", "Blogg", "FAQ", "Kontakt", "Om oss"], whatsappLabel: "Skriv til PaintLab Torrevieja på WhatsApp", faqHeading: "Ofte stilte spørsmål", notFoundBack: "Tilbake til forsiden", dateLocale: "nb-NO", ratingAction: "Sett vurderingen til {rating} av 5", ratingOutOfFive: "av 5" },
  fi: { mainNavigation: "Päänavigointi", languageMenu: "Kieli", menu: "Valikko", footerNavigation: "Sivuston osiot", footerLinks: ["Palvelut", "Kaupungit", "Automerkit", "Työt", "Blogi", "FAQ", "Yhteystiedot", "Tietoa meistä"], whatsappLabel: "Kirjoita PaintLab Torreviejalle WhatsAppissa", faqHeading: "Usein kysytyt kysymykset", notFoundBack: "Takaisin etusivulle", dateLocale: "fi-FI", ratingAction: "Aseta arvosanaksi {rating}/5", ratingOutOfFive: "/ 5" },
  da: { mainNavigation: "Hovednavigation", languageMenu: "Sprog", menu: "Menu", footerNavigation: "Webstedets sektioner", footerLinks: ["Ydelser", "Byer", "Bilmærker", "Arbejder", "Blog", "FAQ", "Kontakt", "Om os"], whatsappLabel: "Skriv til PaintLab Torrevieja på WhatsApp", faqHeading: "Ofte stillede spørgsmål", notFoundBack: "Tilbage til forsiden", dateLocale: "da-DK", ratingAction: "Angiv bedømmelsen til {rating} af 5", ratingOutOfFive: "af 5" },
  sv: { mainNavigation: "Huvudnavigering", languageMenu: "Språk", menu: "Meny", footerNavigation: "Webbplatsens delar", footerLinks: ["Tjänster", "Städer", "Bilmärken", "Arbeten", "Blogg", "FAQ", "Kontakt", "Om oss"], whatsappLabel: "Skriv till PaintLab Torrevieja på WhatsApp", faqHeading: "Vanliga frågor", notFoundBack: "Tillbaka till startsidan", dateLocale: "sv-SE", ratingAction: "Sätt betyget till {rating} av 5", ratingOutOfFive: "av 5" },
  sk: { mainNavigation: "Hlavná navigácia", languageMenu: "Jazyk", menu: "Menu", footerNavigation: "Časti webu", footerLinks: ["Služby", "Mestá", "Značky", "Práce", "Blog", "FAQ", "Kontakt", "O nás"], whatsappLabel: "Napísať PaintLab Torrevieja cez WhatsApp", faqHeading: "Časté otázky", notFoundBack: "Späť na úvod", dateLocale: "sk-SK", ratingAction: "Nastaviť hodnotenie na {rating} z 5", ratingOutOfFive: "z 5" },
  hu: { mainNavigation: "Fő navigáció", languageMenu: "Nyelv", menu: "Menü", footerNavigation: "Webhelyrészek", footerLinks: ["Szolgáltatások", "Városok", "Márkák", "Munkák", "Blog", "FAQ", "Kapcsolat", "Rólunk"], whatsappLabel: "Írjon a PaintLab Torreviejának WhatsAppon", faqHeading: "Gyakori kérdések", notFoundBack: "Vissza a kezdőlapra", dateLocale: "hu-HU", ratingAction: "Értékelés beállítása: {rating} az 5-ből", ratingOutOfFive: "az 5-ből" },
  bg: { mainNavigation: "Основна навигация", languageMenu: "Език", menu: "Меню", footerNavigation: "Раздели на сайта", footerLinks: ["Услуги", "Градове", "Марки", "Работи", "Блог", "FAQ", "Контакти", "За нас"], whatsappLabel: "Пишете на PaintLab Torrevieja в WhatsApp", faqHeading: "Често задавани въпроси", notFoundBack: "Обратно към началото", dateLocale: "bg-BG", ratingAction: "Задаване на оценка {rating} от 5", ratingOutOfFive: "от 5" },
  pt: { mainNavigation: "Navegação principal", languageMenu: "Idioma", menu: "Menu", footerNavigation: "Secções do site", footerLinks: ["Serviços", "Cidades", "Marcas", "Trabalhos", "Blog", "FAQ", "Contacto", "Sobre nós"], whatsappLabel: "Escrever à PaintLab Torrevieja no WhatsApp", faqHeading: "Perguntas frequentes", notFoundBack: "Voltar ao início", dateLocale: "pt-PT", ratingAction: "Definir a classificação como {rating} de 5", ratingOutOfFive: "de 5" },
  el: { mainNavigation: "Κύρια πλοήγηση", languageMenu: "Γλώσσα", menu: "Μενού", footerNavigation: "Ενότητες ιστοτόπου", footerLinks: ["Υπηρεσίες", "Πόλεις", "Μάρκες", "Εργασίες", "Blog", "FAQ", "Επικοινωνία", "Σχετικά με εμάς"], whatsappLabel: "Μήνυμα στο PaintLab Torrevieja μέσω WhatsApp", faqHeading: "Συχνές ερωτήσεις", notFoundBack: "Επιστροφή στην αρχική", dateLocale: "el-GR", ratingAction: "Ορισμός βαθμολογίας σε {rating} από 5", ratingOutOfFive: "από 5" },
  cs: { mainNavigation: "Hlavní navigace", languageMenu: "Jazyk", menu: "Menu", footerNavigation: "Části webu", footerLinks: ["Služby", "Města", "Značky", "Práce", "Blog", "FAQ", "Kontakt", "O nás"], whatsappLabel: "Napsat PaintLab Torrevieja přes WhatsApp", faqHeading: "Časté dotazy", notFoundBack: "Zpět na úvod", dateLocale: "cs-CZ", ratingAction: "Nastavit hodnocení na {rating} z 5", ratingOutOfFive: "z 5" },
};
