import type { Locale } from "@/config/i18n";

type PrivacyCopy = { title: string; paragraphs: readonly string[]; back: string };

export const privacyTranslations: Record<Locale, PrivacyCopy> = {
  es: { title: "Política de privacidad", paragraphs: ["Los datos enviados mediante el formulario de opiniones se utilizan únicamente para revisar, moderar y, si procede, publicar la opinión.", "Tratamos el nombre, la valoración, el servicio indicado y el texto de la opinión. Los datos técnicos de seguridad se conservan solo para prevenir abuso y spam.", "Puedes solicitar la revisión o eliminación de tus datos contactando con Pintura Torrevieja por WhatsApp."], back: "Volver al sitio" },
  en: { title: "Privacy policy", paragraphs: ["Data submitted through the review form is used only to review, moderate and, where appropriate, publish the review.", "We process the name, rating, stated service and review text. Technical security data is retained only to prevent abuse and spam.", "You may request access to or deletion of your data by contacting Pintura Torrevieja via WhatsApp."], back: "Back to the website" },
  ru: { title: "Политика конфиденциальности", paragraphs: ["Данные из формы отзывов используются только для проверки, модерации и, при одобрении, публикации отзыва.", "Мы обрабатываем имя, оценку, указанную услугу и текст отзыва. Технические данные безопасности используются только для защиты от злоупотреблений и спама.", "Вы можете запросить проверку или удаление своих данных, связавшись с Pintura Torrevieja через WhatsApp."], back: "Вернуться на сайт" },
  uk: { title: "Політика конфіденційності", paragraphs: ["Дані з форми відгуків використовуються лише для перевірки, модерації та, після схвалення, публікації відгуку.", "Ми обробляємо ім’я, оцінку, зазначену послугу та текст відгуку. Технічні дані використовуються лише для захисту від зловживань і спаму.", "Ви можете запросити перевірку або видалення даних, звернувшись до Pintura Torrevieja через WhatsApp."], back: "Повернутися на сайт" },
  de: { title: "Datenschutzerklärung", paragraphs: ["Die über das Bewertungsformular übermittelten Daten werden ausschließlich zur Prüfung, Moderation und gegebenenfalls Veröffentlichung der Bewertung verwendet.", "Wir verarbeiten Name, Bewertung, angegebene Leistung und Bewertungstext. Technische Sicherheitsdaten dienen nur der Missbrauchs- und Spamabwehr.", "Sie können die Prüfung oder Löschung Ihrer Daten über WhatsApp bei Pintura Torrevieja anfordern."], back: "Zurück zur Website" },
  fr: { title: "Politique de confidentialité", paragraphs: ["Les données envoyées via le formulaire d’avis sont utilisées uniquement pour vérifier, modérer et, le cas échéant, publier l’avis.", "Nous traitons le nom, la note, le service indiqué et le texte de l’avis. Les données techniques servent uniquement à prévenir les abus et le spam.", "Vous pouvez demander la consultation ou la suppression de vos données via WhatsApp auprès de Pintura Torrevieja."], back: "Retour au site" },
  pl: { title: "Polityka prywatności", paragraphs: ["Dane przesłane przez formularz opinii służą wyłącznie do weryfikacji, moderacji i ewentualnej publikacji opinii.", "Przetwarzamy imię, ocenę, wskazaną usługę i treść opinii. Dane techniczne służą wyłącznie ochronie przed nadużyciami i spamem.", "Możesz poprosić o wgląd lub usunięcie danych, kontaktując się z Pintura Torrevieja przez WhatsApp."], back: "Powrót do strony" },
  nl: { title: "Privacybeleid", paragraphs: ["Gegevens uit het beoordelingsformulier worden uitsluitend gebruikt om de beoordeling te controleren, modereren en eventueel te publiceren.", "We verwerken naam, score, opgegeven dienst en beoordelingstekst. Technische gegevens worden alleen gebruikt om misbruik en spam te voorkomen.", "U kunt inzage of verwijdering aanvragen via WhatsApp bij Pintura Torrevieja."], back: "Terug naar de website" },
  it: { title: "Informativa sulla privacy", paragraphs: ["I dati inviati tramite il modulo recensioni vengono usati esclusivamente per verificare, moderare ed eventualmente pubblicare la recensione.", "Trattiamo nome, valutazione, servizio indicato e testo. I dati tecnici servono solo a prevenire abusi e spam.", "Puoi richiedere la verifica o la cancellazione dei dati contattando Pintura Torrevieja tramite WhatsApp."], back: "Torna al sito" },
  nb: { title: "Personvernerklæring", paragraphs: ["Data fra anmeldelsesskjemaet brukes bare til kontroll, moderering og eventuell publisering.", "Vi behandler navn, vurdering, oppgitt arbeid og anmeldelsestekst. Tekniske data brukes kun for å hindre misbruk og spam.", "Du kan be om innsyn eller sletting ved å kontakte PaintLab Torrevieja via WhatsApp."], back: "Tilbake til nettstedet" },
  fi: { title: "Tietosuojakäytäntö", paragraphs: ["Arviointilomakkeen tietoja käytetään vain tarkistamiseen, moderointiin ja hyväksytyn arvion julkaisemiseen.", "Käsittelemme nimen, arvosanan, ilmoitetun työn ja arvion tekstin. Teknisiä tietoja käytetään vain väärinkäytösten ja roskapostin estämiseen.", "Voit pyytää tietojen tarkistamista tai poistamista ottamalla yhteyttä PaintLab Torreviejaan WhatsAppissa."], back: "Takaisin sivustolle" },
  da: { title: "Privatlivspolitik", paragraphs: ["Data fra anmeldelsesformularen bruges kun til kontrol, moderering og eventuel offentliggørelse.", "Vi behandler navn, bedømmelse, oplyst arbejde og anmeldelsestekst. Tekniske data bruges kun til at forhindre misbrug og spam.", "Du kan bede om indsigt eller sletning ved at kontakte PaintLab Torrevieja via WhatsApp."], back: "Tilbage til hjemmesiden" },
  sv: { title: "Integritetspolicy", paragraphs: ["Uppgifter från omdömesformuläret används endast för granskning, moderering och eventuell publicering.", "Vi behandlar namn, betyg, angivet arbete och omdömestext. Tekniska uppgifter används endast för att förhindra missbruk och spam.", "Du kan begära tillgång eller radering genom att kontakta PaintLab Torrevieja via WhatsApp."], back: "Tillbaka till webbplatsen" },
  sk: { title: "Zásady ochrany súkromia", paragraphs: ["Údaje z formulára hodnotenia používame iba na kontrolu, moderovanie a prípadné zverejnenie.", "Spracúvame meno, hodnotenie, uvedenú prácu a text hodnotenia. Technické údaje slúžia iba na ochranu pred zneužitím a spamom.", "O kontrolu alebo vymazanie údajov môžete požiadať cez WhatsApp PaintLab Torrevieja."], back: "Späť na web" },
  hu: { title: "Adatvédelmi szabályzat", paragraphs: ["Az értékelési űrlap adatait kizárólag ellenőrzésre, moderálásra és jóváhagyás esetén közzétételre használjuk.", "A nevet, értékelést, megadott munkát és a vélemény szövegét kezeljük. A technikai adatokat csak a visszaélések és spam megelőzésére használjuk.", "Adatai ellenőrzését vagy törlését a PaintLab Torrevieja WhatsApp-elérhetőségén kérheti."], back: "Vissza a webhelyre" },
  bg: { title: "Политика за поверителност", paragraphs: ["Данните от формуляра за отзиви се използват само за проверка, модериране и евентуално публикуване.", "Обработваме името, оценката, посочената работа и текста на отзива. Техническите данни се използват само срещу злоупотреби и спам.", "Можете да поискате проверка или изтриване на данните чрез WhatsApp на PaintLab Torrevieja."], back: "Обратно към сайта" },
  pt: { title: "Política de privacidade", paragraphs: ["Os dados do formulário de avaliações são usados apenas para verificação, moderação e eventual publicação.", "Tratamos o nome, a classificação, o trabalho indicado e o texto da avaliação. Os dados técnicos servem apenas para prevenir abuso e spam.", "Pode pedir acesso ou eliminação dos dados contactando a PaintLab Torrevieja por WhatsApp."], back: "Voltar ao site" },
  el: { title: "Πολιτική απορρήτου", paragraphs: ["Τα δεδομένα της φόρμας αξιολόγησης χρησιμοποιούνται μόνο για έλεγχο, εποπτεία και ενδεχόμενη δημοσίευση.", "Επεξεργαζόμαστε το όνομα, τη βαθμολογία, την αναφερόμενη εργασία και το κείμενο. Τα τεχνικά δεδομένα χρησιμοποιούνται μόνο κατά της κατάχρησης και του spam.", "Μπορείτε να ζητήσετε έλεγχο ή διαγραφή μέσω WhatsApp από το PaintLab Torrevieja."], back: "Επιστροφή στον ιστότοπο" },
  cs: { title: "Zásady ochrany soukromí", paragraphs: ["Údaje z formuláře hodnocení používáme pouze ke kontrole, moderování a případnému zveřejnění.", "Zpracováváme jméno, hodnocení, uvedenou práci a text hodnocení. Technické údaje slouží pouze k ochraně proti zneužití a spamu.", "O kontrolu nebo smazání údajů můžete požádat přes WhatsApp PaintLab Torrevieja."], back: "Zpět na web" },
};
