import type { Locale } from "@/config/i18n";

type PrivacyCopy = { title: string; paragraphs: readonly string[]; back: string };

export const privacyTranslations: Record<Locale, PrivacyCopy> = {
  es: { title: "Política de privacidad", paragraphs: ["Los datos enviados mediante el formulario de opiniones se utilizan únicamente para revisar, moderar y, si procede, publicar la opinión.", "Tratamos el nombre, la valoración, el servicio indicado y el texto de la opinión. Los datos técnicos de seguridad se conservan solo para prevenir abuso y spam.", "Puedes solicitar la revisión o eliminación de tus datos contactando con Pintura Torrevieja por WhatsApp."], back: "Volver al sitio" },
  en: { title: "Privacy policy", paragraphs: ["Data submitted through the review form is used only to review, moderate and, where appropriate, publish the review.", "We process the name, rating, stated service and review text. Technical security data is retained only to prevent abuse and spam.", "You may request access to or deletion of your data by contacting Pintura Torrevieja via WhatsApp."], back: "Back to the website" },
  ru: { title: "Политика конфиденциальности", paragraphs: ["Данные из формы отзывов используются только для проверки, модерации и, при одобрении, публикации отзыва.", "Мы обрабатываем имя, оценку, указанную услугу и текст отзыва. Технические данные безопасности используются только для защиты от злоупотреблений и спама.", "Вы можете запросить проверку или удаление своих данных, связавшись с Pintura Torrevieja через WhatsApp."], back: "Вернуться на сайт" },
  uk: { title: "Політика конфіденційності", paragraphs: ["Дані з форми відгуків використовуються лише для перевірки, модерації та, після схвалення, публікації відгуку.", "Ми обробляємо ім’я, оцінку, зазначену послугу та текст відгуку. Технічні дані використовуються лише для захисту від зловживань і спаму.", "Ви можете запросити перевірку або видалення даних, звернувшись до Pintura Torrevieja через WhatsApp."], back: "Повернутися на сайт" },
  de: { title: "Datenschutzerklärung", paragraphs: ["Die über das Bewertungsformular übermittelten Daten werden ausschließlich zur Prüfung, Moderation und gegebenenfalls Veröffentlichung der Bewertung verwendet.", "Wir verarbeiten Name, Bewertung, angegebene Leistung und Bewertungstext. Technische Sicherheitsdaten dienen nur der Missbrauchs- und Spamabwehr.", "Sie können die Prüfung oder Löschung Ihrer Daten über WhatsApp bei Pintura Torrevieja anfordern."], back: "Zurück zur Website" },
  fr: { title: "Politique de confidentialité", paragraphs: ["Les données envoyées via le formulaire d’avis sont utilisées uniquement pour vérifier, modérer et, le cas échéant, publier l’avis.", "Nous traitons le nom, la note, le service indiqué et le texte de l’avis. Les données techniques servent uniquement à prévenir les abus et le spam.", "Vous pouvez demander la consultation ou la suppression de vos données via WhatsApp auprès de Pintura Torrevieja."], back: "Retour au site" },
  pl: { title: "Polityka prywatności", paragraphs: ["Dane przesłane przez formularz opinii służą wyłącznie do weryfikacji, moderacji i ewentualnej publikacji opinii.", "Przetwarzamy imię, ocenę, wskazaną usługę i treść opinii. Dane techniczne służą wyłącznie ochronie przed nadużyciami i spamem.", "Możesz poprosić o wgląd lub usunięcie danych, kontaktując się z Pintura Torrevieja przez WhatsApp."], back: "Powrót do strony" },
  ro: { title: "Politica de confidențialitate", paragraphs: ["Datele trimise prin formularul de recenzii sunt folosite doar pentru verificarea, moderarea și, dacă este cazul, publicarea recenziei.", "Prelucrăm numele, evaluarea, serviciul indicat și textul recenziei. Datele tehnice sunt păstrate doar pentru prevenirea abuzului și spamului.", "Poți solicita verificarea sau ștergerea datelor contactând Pintura Torrevieja prin WhatsApp."], back: "Înapoi la site" },
  nl: { title: "Privacybeleid", paragraphs: ["Gegevens uit het beoordelingsformulier worden uitsluitend gebruikt om de beoordeling te controleren, modereren en eventueel te publiceren.", "We verwerken naam, score, opgegeven dienst en beoordelingstekst. Technische gegevens worden alleen gebruikt om misbruik en spam te voorkomen.", "U kunt inzage of verwijdering aanvragen via WhatsApp bij Pintura Torrevieja."], back: "Terug naar de website" },
  it: { title: "Informativa sulla privacy", paragraphs: ["I dati inviati tramite il modulo recensioni vengono usati esclusivamente per verificare, moderare ed eventualmente pubblicare la recensione.", "Trattiamo nome, valutazione, servizio indicato e testo. I dati tecnici servono solo a prevenire abusi e spam.", "Puoi richiedere la verifica o la cancellazione dei dati contattando Pintura Torrevieja tramite WhatsApp."], back: "Torna al sito" },
};
