import type { Locale } from "@/config/i18n";

export type ProjectsCopy = {
  navLabel: string;
  pageTitle: string;
  pageLead: string;
  home: string;
  before: string;
  after: string;
  sliderAria: string;
  realTitle: string;
  realText: string;
  approachTitle: string;
  approachText: string;
  timingTitle: string;
  timingText: string;
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
  viewProject: string;
  backToWorks: string;
  caseLabel: string;
  beforeState: string;
  workPerformed: string;
  result: string;
  services: string;
  listMetaTitle: string;
  listMetaDescription: string;
};

export const projectsTranslations: Record<Locale, ProjectsCopy> = {
  es: {
    navLabel: "Nuestros trabajos", pageTitle: "Nuestros trabajos", pageLead: "Ejemplos reales de reparación y pintura de vehículos. Antes y después.", home: "Inicio", before: "Antes", after: "Después", sliderAria: "Comparación del Nissan Qashqai antes y después de la reparación", realTitle: "Trabajos reales", realText: "Solo fotografías auténticas antes y después de la reparación.", approachTitle: "Enfoque profesional", approachText: "Materiales de calidad y atención a los detalles.", timingTitle: "Cumplimos los plazos", timingText: "Organizamos el trabajo sin retrasos innecesarios.", ctaTitle: "¿Necesitas un resultado así?", ctaText: "Envía fotos del vehículo por WhatsApp y recibe una estimación previa.", ctaButton: "Escribir en WhatsApp", viewProject: "Ver trabajo", backToWorks: "Volver a nuestros trabajos", caseLabel: "Trabajo real", beforeState: "Estado antes de la reparación", workPerformed: "Trabajo realizado", result: "Resultado", services: "Proceso realizado", listMetaTitle: "Trabajos de chapa y pintura en Torrevieja | PaintLab", listMetaDescription: "Trabajos reales de chapa y pintura en Torrevieja. Consulta ejemplos antes y después y solicita una estimación previa por WhatsApp.",
  },
  en: {
    navLabel: "Our work", pageTitle: "Our work", pageLead: "Real examples of vehicle body repair and painting. Before and after.", home: "Home", before: "Before", after: "After", sliderAria: "Nissan Qashqai before and after repair comparison", realTitle: "Real work", realText: "Only genuine photographs taken before and after repair.", approachTitle: "Professional approach", approachText: "Quality materials and attention to detail.", timingTitle: "Work kept on schedule", timingText: "We organise each job without unnecessary delays.", ctaTitle: "Need a result like this?", ctaText: "Send vehicle photos on WhatsApp for a preliminary estimate.", ctaButton: "Write on WhatsApp", viewProject: "View project", backToWorks: "Back to our work", caseLabel: "Real project", beforeState: "Condition before repair", workPerformed: "Work performed", result: "Result", services: "Work process", listMetaTitle: "Car body repair work in Torrevieja | PaintLab", listMetaDescription: "Real car body repair and painting work in Torrevieja. See before-and-after results and request a preliminary estimate via WhatsApp.",
  },
  ru: {
    navLabel: "Наши работы", pageTitle: "Наши работы", pageLead: "Реальные примеры ремонта и покраски автомобилей. До и после.", home: "Главная", before: "До", after: "После", sliderAria: "Сравнение Nissan Qashqai до и после ремонта", realTitle: "Реальные работы", realText: "Только настоящие фотографии до и после ремонта.", approachTitle: "Профессиональный подход", approachText: "Качественные материалы и внимание к деталям.", timingTitle: "Соблюдаем сроки", timingText: "Организуем работу без ненужных задержек.", ctaTitle: "Нужен такой же результат?", ctaText: "Отправьте фото автомобиля в WhatsApp и получите предварительную оценку.", ctaButton: "Написать в WhatsApp", viewProject: "Открыть работу", backToWorks: "Вернуться к нашим работам", caseLabel: "Реальная работа", beforeState: "Состояние до ремонта", workPerformed: "Выполненная работа", result: "Результат", services: "Этапы работы", listMetaTitle: "Примеры кузовного ремонта и покраски | PaintLab", listMetaDescription: "Реальные работы по кузовному ремонту и покраске автомобилей в Торревьехе. Смотрите фото до и после и отправляйте фото для оценки в WhatsApp.",
  },
  uk: {
    navLabel: "Наші роботи", pageTitle: "Наші роботи", pageLead: "Реальні приклади ремонту та фарбування автомобілів. До і після.", home: "Головна", before: "До", after: "Після", sliderAria: "Порівняння Nissan Qashqai до і після ремонту", realTitle: "Реальні роботи", realText: "Тільки справжні фотографії до і після ремонту.", approachTitle: "Професійний підхід", approachText: "Якісні матеріали та увага до деталей.", timingTitle: "Дотримуємося строків", timingText: "Організовуємо роботу без зайвих затримок.", ctaTitle: "Потрібен такий самий результат?", ctaText: "Надішліть фото автомобіля у WhatsApp і отримайте попередню оцінку.", ctaButton: "Написати у WhatsApp", viewProject: "Відкрити роботу", backToWorks: "Повернутися до наших робіт", caseLabel: "Реальна робота", beforeState: "Стан до ремонту", workPerformed: "Виконана робота", result: "Результат", services: "Етапи роботи", listMetaTitle: "Приклади кузовного ремонту та фарбування | PaintLab", listMetaDescription: "Реальні роботи з кузовного ремонту та фарбування автомобілів у Торрев’єсі. Перегляньте фото до і після та надішліть фото для оцінки у WhatsApp.",
  },
  de: {
    navLabel: "Unsere Arbeiten", pageTitle: "Unsere Arbeiten", pageLead: "Echte Beispiele für Karosseriereparatur und Fahrzeuglackierung. Vorher und nachher.", home: "Start", before: "Vorher", after: "Nachher", sliderAria: "Nissan Qashqai vor und nach der Reparatur", realTitle: "Echte Arbeiten", realText: "Ausschließlich echte Fotos vor und nach der Reparatur.", approachTitle: "Professioneller Ansatz", approachText: "Hochwertige Materialien und Sorgfalt im Detail.", timingTitle: "Verlässliche Planung", timingText: "Wir organisieren die Arbeit ohne unnötige Verzögerungen.", ctaTitle: "Wünschen Sie ein ähnliches Ergebnis?", ctaText: "Senden Sie Fahrzeugfotos per WhatsApp für eine erste Einschätzung.", ctaButton: "Auf WhatsApp schreiben", viewProject: "Arbeit ansehen", backToWorks: "Zurück zu unseren Arbeiten", caseLabel: "Echte Arbeit", beforeState: "Zustand vor der Reparatur", workPerformed: "Ausgeführte Arbeiten", result: "Ergebnis", services: "Arbeitsablauf", listMetaTitle: "Karosserie- und Lackierarbeiten in Torrevieja | PaintLab", listMetaDescription: "Echte Karosserie- und Lackierarbeiten in Torrevieja. Sehen Sie Vorher-Nachher-Ergebnisse und senden Sie Fotos per WhatsApp.",
  },
  fr: {
    navLabel: "Nos réalisations", pageTitle: "Nos réalisations", pageLead: "Exemples réels de réparation et de peinture automobile. Avant et après.", home: "Accueil", before: "Avant", after: "Après", sliderAria: "Comparaison du Nissan Qashqai avant et après réparation", realTitle: "Réalisations réelles", realText: "Uniquement de vraies photos avant et après réparation.", approachTitle: "Approche professionnelle", approachText: "Des matériaux de qualité et le souci du détail.", timingTitle: "Délais respectés", timingText: "Nous organisons le travail sans retards inutiles.", ctaTitle: "Vous souhaitez un résultat similaire ?", ctaText: "Envoyez des photos du véhicule sur WhatsApp pour une estimation préalable.", ctaButton: "Écrire sur WhatsApp", viewProject: "Voir la réalisation", backToWorks: "Retour à nos réalisations", caseLabel: "Réalisation réelle", beforeState: "État avant réparation", workPerformed: "Travail effectué", result: "Résultat", services: "Étapes du travail", listMetaTitle: "Réalisations de carrosserie à Torrevieja | PaintLab", listMetaDescription: "Réalisations réelles de carrosserie et peinture à Torrevieja. Découvrez les résultats avant-après et demandez une estimation via WhatsApp.",
  },
  pl: {
    navLabel: "Nasze realizacje", pageTitle: "Nasze realizacje", pageLead: "Prawdziwe przykłady napraw blacharskich i lakierowania. Przed i po.", home: "Start", before: "Przed", after: "Po", sliderAria: "Porównanie Nissan Qashqai przed i po naprawie", realTitle: "Prawdziwe realizacje", realText: "Wyłącznie autentyczne zdjęcia przed naprawą i po niej.", approachTitle: "Profesjonalne podejście", approachText: "Materiały wysokiej jakości i dbałość o szczegóły.", timingTitle: "Dotrzymujemy terminów", timingText: "Organizujemy pracę bez niepotrzebnych opóźnień.", ctaTitle: "Potrzebujesz podobnego efektu?", ctaText: "Wyślij zdjęcia samochodu przez WhatsApp, aby uzyskać wstępną ocenę.", ctaButton: "Napisz na WhatsApp", viewProject: "Zobacz realizację", backToWorks: "Wróć do realizacji", caseLabel: "Prawdziwa realizacja", beforeState: "Stan przed naprawą", workPerformed: "Wykonane prace", result: "Efekt", services: "Etapy pracy", listMetaTitle: "Realizacje napraw blacharskich w Torrevieja | PaintLab", listMetaDescription: "Prawdziwe naprawy blacharskie i lakierowanie w Torrevieja. Zobacz efekty przed i po oraz wyślij zdjęcia przez WhatsApp.",
  },
  nl: {
    navLabel: "Ons werk", pageTitle: "Ons werk", pageLead: "Echte voorbeelden van autoschadeherstel en spuitwerk. Voor en na.", home: "Home", before: "Voor", after: "Na", sliderAria: "Nissan Qashqai voor en na de reparatie", realTitle: "Echt uitgevoerd werk", realText: "Alleen authentieke foto's van vóór en na de reparatie.", approachTitle: "Professionele aanpak", approachText: "Kwaliteitsmaterialen en aandacht voor details.", timingTitle: "Volgens planning", timingText: "Wij organiseren het werk zonder onnodige vertraging.", ctaTitle: "Een vergelijkbaar resultaat nodig?", ctaText: "Stuur voertuigfoto's via WhatsApp voor een voorlopige inschatting.", ctaButton: "Schrijf op WhatsApp", viewProject: "Project bekijken", backToWorks: "Terug naar ons werk", caseLabel: "Echt project", beforeState: "Staat vóór reparatie", workPerformed: "Uitgevoerde werkzaamheden", result: "Resultaat", services: "Werkproces", listMetaTitle: "Autoschadeherstel in Torrevieja | PaintLab", listMetaDescription: "Echt autoschadeherstel en spuitwerk in Torrevieja. Bekijk voor-en-naresultaten en stuur foto's via WhatsApp.",
  },
  it: {
    navLabel: "I nostri lavori", pageTitle: "I nostri lavori", pageLead: "Esempi reali di riparazione e verniciatura auto. Prima e dopo.", home: "Home", before: "Prima", after: "Dopo", sliderAria: "Confronto Nissan Qashqai prima e dopo la riparazione", realTitle: "Lavori reali", realText: "Solo fotografie autentiche prima e dopo la riparazione.", approachTitle: "Approccio professionale", approachText: "Materiali di qualità e attenzione ai dettagli.", timingTitle: "Rispettiamo i tempi", timingText: "Organizziamo il lavoro senza ritardi inutili.", ctaTitle: "Vuoi un risultato simile?", ctaText: "Invia le foto del veicolo su WhatsApp per una valutazione preliminare.", ctaButton: "Scrivi su WhatsApp", viewProject: "Vedi il lavoro", backToWorks: "Torna ai nostri lavori", caseLabel: "Lavoro reale", beforeState: "Condizioni prima della riparazione", workPerformed: "Lavoro eseguito", result: "Risultato", services: "Fasi del lavoro", listMetaTitle: "Lavori di carrozzeria a Torrevieja | PaintLab", listMetaDescription: "Lavori reali di carrozzeria e verniciatura a Torrevieja. Guarda i risultati prima e dopo e invia le foto su WhatsApp.",
  },
  nb: {
    navLabel: "Våre arbeider", pageTitle: "Våre arbeider", pageLead: "Ekte eksempler på karosserireparasjon og billakkering. Før og etter.", home: "Hjem", before: "Før", after: "Etter", sliderAria: "Nissan Qashqai før og etter reparasjon", realTitle: "Ekte arbeider", realText: "Kun autentiske bilder før og etter reparasjon.", approachTitle: "Profesjonell tilnærming", approachText: "Kvalitetsmaterialer og oppmerksomhet på detaljer.", timingTitle: "Vi følger planen", timingText: "Vi organiserer arbeidet uten unødvendige forsinkelser.", ctaTitle: "Trenger du et lignende resultat?", ctaText: "Send bilder av bilen på WhatsApp for en foreløpig vurdering.", ctaButton: "Skriv på WhatsApp", viewProject: "Se arbeidet", backToWorks: "Tilbake til våre arbeider", caseLabel: "Ekte arbeid", beforeState: "Tilstand før reparasjon", workPerformed: "Utført arbeid", result: "Resultat", services: "Arbeidsprosess", listMetaTitle: "Karosseriarbeid i Torrevieja | PaintLab", listMetaDescription: "Ekte karosseri- og lakkeringsarbeid i Torrevieja. Se før-og-etter-resultater og send bilder via WhatsApp.",
  },
  fi: {
    navLabel: "Työmme", pageTitle: "Työmme", pageLead: "Aitoja esimerkkejä korikorjauksesta ja automaalauksesta. Ennen ja jälkeen.", home: "Etusivu", before: "Ennen", after: "Jälkeen", sliderAria: "Nissan Qashqai ennen korjausta ja sen jälkeen", realTitle: "Aidot työt", realText: "Vain aitoja kuvia ennen korjausta ja sen jälkeen.", approachTitle: "Ammattimainen työote", approachText: "Laadukkaat materiaalit ja huolellinen viimeistely.", timingTitle: "Työ etenee suunnitellusti", timingText: "Järjestämme työn ilman tarpeettomia viivästyksiä.", ctaTitle: "Tarvitsetko vastaavan tuloksen?", ctaText: "Lähetä kuvat autosta WhatsAppissa alustavaa arviota varten.", ctaButton: "Kirjoita WhatsAppissa", viewProject: "Katso työ", backToWorks: "Takaisin töihimme", caseLabel: "Aito työ", beforeState: "Kunto ennen korjausta", workPerformed: "Tehty työ", result: "Tulos", services: "Työvaiheet", listMetaTitle: "Korikorjaustyöt Torreviejassa | PaintLab", listMetaDescription: "Aitoja korikorjaus- ja maalaustöitä Torreviejassa. Katso ennen ja jälkeen -tulokset ja lähetä kuvat WhatsAppissa.",
  },
  da: {
    navLabel: "Vores arbejde", pageTitle: "Vores arbejde", pageLead: "Ægte eksempler på karrosserireparation og billakering. Før og efter.", home: "Forside", before: "Før", after: "Efter", sliderAria: "Nissan Qashqai før og efter reparation", realTitle: "Virkeligt arbejde", realText: "Kun autentiske billeder før og efter reparation.", approachTitle: "Professionel tilgang", approachText: "Kvalitetsmaterialer og sans for detaljen.", timingTitle: "Vi følger tidsplanen", timingText: "Vi organiserer arbejdet uden unødvendige forsinkelser.", ctaTitle: "Har du brug for et lignende resultat?", ctaText: "Send billeder af bilen på WhatsApp for en foreløbig vurdering.", ctaButton: "Skriv på WhatsApp", viewProject: "Se arbejdet", backToWorks: "Tilbage til vores arbejde", caseLabel: "Virkeligt arbejde", beforeState: "Tilstand før reparation", workPerformed: "Udført arbejde", result: "Resultat", services: "Arbejdsproces", listMetaTitle: "Karrosseriarbejde i Torrevieja | PaintLab", listMetaDescription: "Virkelige karrosseri- og lakeringsarbejder i Torrevieja. Se før-og-efter-resultater og send billeder via WhatsApp.",
  },
  sv: {
    navLabel: "Våra arbeten", pageTitle: "Våra arbeten", pageLead: "Verkliga exempel på karosserireparation och billackering. Före och efter.", home: "Start", before: "Före", after: "Efter", sliderAria: "Nissan Qashqai före och efter reparation", realTitle: "Verkliga arbeten", realText: "Endast autentiska bilder före och efter reparation.", approachTitle: "Professionellt arbetssätt", approachText: "Kvalitetsmaterial och omsorg om detaljerna.", timingTitle: "Vi håller tidsplanen", timingText: "Vi organiserar arbetet utan onödiga förseningar.", ctaTitle: "Behöver du ett liknande resultat?", ctaText: "Skicka bilder av bilen via WhatsApp för en preliminär bedömning.", ctaButton: "Skriv på WhatsApp", viewProject: "Se arbetet", backToWorks: "Tillbaka till våra arbeten", caseLabel: "Verkligt arbete", beforeState: "Skick före reparation", workPerformed: "Utfört arbete", result: "Resultat", services: "Arbetsmoment", listMetaTitle: "Karosseriarbeten i Torrevieja | PaintLab", listMetaDescription: "Verkliga karosseri- och lackeringsarbeten i Torrevieja. Se före-och-efter-resultat och skicka bilder via WhatsApp.",
  },
  sk: {
    navLabel: "Naše práce", pageTitle: "Naše práce", pageLead: "Skutočné príklady opráv karosérie a lakovania vozidiel. Pred a po.", home: "Domov", before: "Pred", after: "Po", sliderAria: "Nissan Qashqai pred a po oprave", realTitle: "Skutočné práce", realText: "Iba autentické fotografie pred opravou a po nej.", approachTitle: "Profesionálny prístup", approachText: "Kvalitné materiály a pozornosť venovaná detailom.", timingTitle: "Dodržiavame termíny", timingText: "Prácu organizujeme bez zbytočných prieťahov.", ctaTitle: "Potrebujete podobný výsledok?", ctaText: "Pošlite fotografie vozidla cez WhatsApp na predbežné posúdenie.", ctaButton: "Napísať cez WhatsApp", viewProject: "Pozrieť prácu", backToWorks: "Späť na naše práce", caseLabel: "Skutočná práca", beforeState: "Stav pred opravou", workPerformed: "Vykonaná práca", result: "Výsledok", services: "Priebeh práce", listMetaTitle: "Opravy karosérie v Torrevieja | PaintLab", listMetaDescription: "Skutočné opravy karosérie a lakovanie v Torrevieja. Pozrite si výsledky pred a po a pošlite fotografie cez WhatsApp.",
  },
  hu: {
    navLabel: "Munkáink", pageTitle: "Munkáink", pageLead: "Valós példák karosszériajavításra és autófényezésre. Előtte és utána.", home: "Kezdőlap", before: "Előtte", after: "Utána", sliderAria: "Nissan Qashqai a javítás előtt és után", realTitle: "Valós munkák", realText: "Kizárólag valódi fényképek a javítás előtti és utáni állapotról.", approachTitle: "Professzionális hozzáállás", approachText: "Minőségi anyagok és figyelem a részletekre.", timingTitle: "Tartjuk az ütemezést", timingText: "A munkát felesleges késedelem nélkül szervezzük.", ctaTitle: "Hasonló eredményre van szüksége?", ctaText: "Küldjön fotókat az autóról WhatsAppon előzetes felméréshez.", ctaButton: "Írjon WhatsAppon", viewProject: "Munka megtekintése", backToWorks: "Vissza a munkáinkhoz", caseLabel: "Valós munka", beforeState: "Állapot javítás előtt", workPerformed: "Elvégzett munka", result: "Eredmény", services: "Munkafolyamat", listMetaTitle: "Karosszériajavítási munkák Torreviejában | PaintLab", listMetaDescription: "Valós karosszériajavítások és fényezések Torreviejában. Tekintse meg az előtte-utána eredményeket, és küldjön képet WhatsAppon.",
  },
  bg: {
    navLabel: "Нашите проекти", pageTitle: "Нашите проекти", pageLead: "Реални примери за каросериен ремонт и боядисване. Преди и след.", home: "Начало", before: "Преди", after: "След", sliderAria: "Nissan Qashqai преди и след ремонта", realTitle: "Реални проекти", realText: "Само истински снимки преди и след ремонта.", approachTitle: "Професионален подход", approachText: "Качествени материали и внимание към детайлите.", timingTitle: "Спазваме сроковете", timingText: "Организираме работата без ненужни забавяния.", ctaTitle: "Нуждаете се от подобен резултат?", ctaText: "Изпратете снимки на автомобила по WhatsApp за предварителна оценка.", ctaButton: "Пишете в WhatsApp", viewProject: "Вижте проекта", backToWorks: "Обратно към проектите", caseLabel: "Реален проект", beforeState: "Състояние преди ремонта", workPerformed: "Извършена работа", result: "Резултат", services: "Етапи на работа", listMetaTitle: "Каросерийни ремонти в Торевиеха | PaintLab", listMetaDescription: "Реални каросерийни ремонти и боядисване в Торевиеха. Вижте резултатите преди и след и изпратете снимки по WhatsApp.",
  },
  pt: {
    navLabel: "Os nossos trabalhos", pageTitle: "Os nossos trabalhos", pageLead: "Exemplos reais de reparação de carroçaria e pintura automóvel. Antes e depois.", home: "Início", before: "Antes", after: "Depois", sliderAria: "Nissan Qashqai antes e depois da reparação", realTitle: "Trabalhos reais", realText: "Apenas fotografias autênticas antes e depois da reparação.", approachTitle: "Abordagem profissional", approachText: "Materiais de qualidade e atenção aos detalhes.", timingTitle: "Cumprimos os prazos", timingText: "Organizamos o trabalho sem atrasos desnecessários.", ctaTitle: "Precisa de um resultado semelhante?", ctaText: "Envie fotografias do veículo por WhatsApp para uma avaliação prévia.", ctaButton: "Escrever no WhatsApp", viewProject: "Ver trabalho", backToWorks: "Voltar aos nossos trabalhos", caseLabel: "Trabalho real", beforeState: "Estado antes da reparação", workPerformed: "Trabalho realizado", result: "Resultado", services: "Etapas do trabalho", listMetaTitle: "Trabalhos de carroçaria em Torrevieja | PaintLab", listMetaDescription: "Trabalhos reais de carroçaria e pintura em Torrevieja. Veja resultados antes e depois e envie fotografias pelo WhatsApp.",
  },
  el: {
    navLabel: "Οι εργασίες μας", pageTitle: "Οι εργασίες μας", pageLead: "Πραγματικά παραδείγματα επισκευής αμαξώματος και βαφής. Πριν και μετά.", home: "Αρχική", before: "Πριν", after: "Μετά", sliderAria: "Nissan Qashqai πριν και μετά την επισκευή", realTitle: "Πραγματικές εργασίες", realText: "Μόνο αυθεντικές φωτογραφίες πριν και μετά την επισκευή.", approachTitle: "Επαγγελματική προσέγγιση", approachText: "Ποιοτικά υλικά και προσοχή στη λεπτομέρεια.", timingTitle: "Τηρούμε τον προγραμματισμό", timingText: "Οργανώνουμε την εργασία χωρίς περιττές καθυστερήσεις.", ctaTitle: "Χρειάζεστε παρόμοιο αποτέλεσμα;", ctaText: "Στείλτε φωτογραφίες του οχήματος μέσω WhatsApp για μια αρχική εκτίμηση.", ctaButton: "Μήνυμα στο WhatsApp", viewProject: "Δείτε την εργασία", backToWorks: "Επιστροφή στις εργασίες μας", caseLabel: "Πραγματική εργασία", beforeState: "Κατάσταση πριν από την επισκευή", workPerformed: "Εργασία που εκτελέστηκε", result: "Αποτέλεσμα", services: "Στάδια εργασίας", listMetaTitle: "Εργασίες αμαξώματος στην Torrevieja | PaintLab", listMetaDescription: "Πραγματικές επισκευές αμαξώματος και βαφές στην Torrevieja. Δείτε αποτελέσματα πριν και μετά και στείλτε φωτογραφίες μέσω WhatsApp.",
  },
  cs: {
    navLabel: "Naše práce", pageTitle: "Naše práce", pageLead: "Skutečné příklady oprav karoserie a lakování vozidel. Před a po.", home: "Domů", before: "Před", after: "Po", sliderAria: "Nissan Qashqai před a po opravě", realTitle: "Skutečné práce", realText: "Pouze autentické fotografie před opravou a po ní.", approachTitle: "Profesionální přístup", approachText: "Kvalitní materiály a pozornost věnovaná detailům.", timingTitle: "Dodržujeme termíny", timingText: "Práci organizujeme bez zbytečných prodlev.", ctaTitle: "Potřebujete podobný výsledek?", ctaText: "Pošlete fotografie vozidla přes WhatsApp pro předběžné posouzení.", ctaButton: "Napsat přes WhatsApp", viewProject: "Zobrazit práci", backToWorks: "Zpět na naše práce", caseLabel: "Skutečná práce", beforeState: "Stav před opravou", workPerformed: "Provedená práce", result: "Výsledek", services: "Průběh práce", listMetaTitle: "Opravy karoserie v Torrevieja | PaintLab", listMetaDescription: "Skutečné opravy karoserie a lakování v Torrevieja. Prohlédněte si výsledky před a po a pošlete fotografie přes WhatsApp.",
  },
};

export function getProjectsPath(locale: Locale) {
  return locale === "es" ? "/trabajos-realizados" : `/${locale}/trabajos-realizados`;
}

export function getProjectPath(locale: Locale, slug: string) {
  return `${getProjectsPath(locale)}/${slug}`;
}
